import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Check, MagnifyingGlass, Minus, Package, Plus, ShieldCheck, ShoppingCart, Trash, WhatsappLogo, X } from "@phosphor-icons/react";
import { usePortfolio } from "@/context/PortfolioContext";
import { NIN_AUTHORITY_NOTICE, NIN_SECURITY_NOTICE, type Product, type ProductCategory } from "@/constants";

const categories: ("All" | ProductCategory)[] = ["All", "MiFi", "4G Routers", "5G Routers", "Portable Wi-Fi", "Other Connectivity Devices"];
const inputCls = "w-full rounded-xl border border-border bg-card px-4 py-2.5 text-sm outline-none transition-colors focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20";

function SectionHeading({ title, subtitle }: { title: string; subtitle: string }) {
  return <div className="mx-auto mb-10 max-w-2xl text-center"><span className="mb-3 inline-block rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">Digital services</span><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">{title}</h2><p className="mt-3 text-muted-foreground">{subtitle}</p></div>;
}

export function QuickCommercialActions() {
  const scroll = (id: string) => document.querySelector(id)?.scrollIntoView({ behavior: "smooth" });
  const actions = [
    ["NIN SERVICES", "Get NIN assistance", "#nin-services", "Get Started"],
    ["MIFI & ROUTERS", "Shop connectivity devices", "#mifi-routers", "Shop Now"],
    ["WEB DEVELOPMENT", "Build your website", "#services", "Hire Me"],
    ["GADGETS", "Explore technology products", "#mifi-routers", "View Products"],
  ];
  return <section className="border-y border-border bg-muted/30 py-6"><div className="mx-auto grid max-w-7xl gap-3 px-5 sm:grid-cols-2 lg:grid-cols-4 lg:px-8">{actions.map(([title, text, href, cta]) => <button key={title} onClick={() => scroll(href)} className="group rounded-2xl border border-border bg-card p-5 text-left transition-all hover:-translate-y-1 hover:border-emerald-500/40 hover:shadow-lg"><div className="text-xs font-bold tracking-wider text-emerald-600 dark:text-emerald-400">{title}</div><div className="mt-1 font-semibold">{text}</div><div className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-blue-600 dark:text-blue-400">{cta}<ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></div></button>)}</div></section>;
}

export function NinServicesSection() {
  const { ninServices, openModal } = usePortfolio();
  const enabled = ninServices.filter((service) => service.enabled);
  return <section id="nin-services" className="border-y border-border bg-slate-950 py-20 text-white lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading title="NIN SERVICES" subtitle="Get Convenient Assistance With Your NIN-Related Services." /><div className="mb-8 grid gap-3 rounded-2xl border border-amber-400/30 bg-amber-400/10 p-5 text-sm text-amber-100"><div className="flex gap-3"><ShieldCheck size={22} className="shrink-0 text-amber-300" /><p>{NIN_SECURITY_NOTICE}</p></div><p className="border-t border-amber-300/20 pt-3">{NIN_AUTHORITY_NOTICE}</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{enabled.map((service) => <motion.article key={service.id} initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="flex h-full flex-col rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur"><div className="mb-4 grid size-11 place-items-center rounded-xl bg-emerald-400/15 text-emerald-300"><ShieldCheck size={23} /></div><h3 className="text-lg font-bold">{service.title}</h3><p className="mt-2 flex-1 text-sm leading-relaxed text-slate-300">{service.description}</p><div className="mt-5 flex items-center justify-between gap-3 border-t border-white/10 pt-4"><span className="text-xs text-slate-400">{service.price}</span><button onClick={() => openModal("nin-request", service.id)} className="rounded-xl bg-emerald-400 px-3 py-2 text-xs font-bold text-slate-950 hover:bg-emerald-300">{service.id === "nin-registration" ? "Request NIN Service" : service.id === "nin-modification" ? "Request Modification" : service.id === "nin-verification" ? "Request Verification" : service.id === "nin-information" ? "Get Assistance" : "Make an Enquiry"}</button></div></motion.article>)}</div>{!enabled.length && <p className="rounded-xl border border-dashed border-white/20 p-8 text-center text-slate-300">NIN services are being updated. Please check back soon.</p>}</div></section>;
}

function formatPrice(price: string) { return price.trim() || "Contact for current price"; }
function numericPrice(price: string) { const value = Number(price.replace(/[^0-9.]/g, "")); return Number.isFinite(value) ? value : 0; }
function productWhatsapp(product: Product, number: string) { return `https://wa.me/234${number.replace(/\D/g, "")}?text=${encodeURIComponent(`Hello Abdullahi, I'm interested in the ${product.name}. Please let me know if it is available and provide the current price and delivery information.`)}`; }

function ProductCard({ product, onDetails }: { product: Product; onDetails: () => void }) {
  const { addToCart, contact, openModal } = usePortfolio();
  return <article className="group overflow-hidden rounded-2xl border border-border bg-card transition-all hover:-translate-y-1 hover:shadow-xl"><button onClick={onDetails} className="relative block aspect-[4/3] w-full overflow-hidden bg-muted text-left">{product.imageUrl ? <img src={product.imageUrl} alt={product.name} className="size-full object-cover transition-transform group-hover:scale-105" /> : <div className="grid size-full place-items-center text-muted-foreground"><Package size={42} /></div>}<span className={`absolute left-3 top-3 rounded-full px-2.5 py-1 text-xs font-bold ${product.availability === "In Stock" ? "bg-emerald-500 text-white" : product.availability === "Low Stock" ? "bg-amber-500 text-white" : "bg-red-500 text-white"}`}>{product.availability}</span></button><div className="p-5"><div className="text-xs text-muted-foreground">{product.brand || "Brand not specified"} · {product.category}</div><h3 className="mt-1 font-bold">{product.name}</h3><p className="mt-1 text-sm text-muted-foreground">{product.networkType} · {product.keySpecification || "Specifications available on request"}</p><div className="mt-4 flex items-center justify-between gap-3"><span className="font-bold text-blue-600 dark:text-blue-400">{formatPrice(product.price)}</span><button onClick={() => openModal("product-detail", product.id)} className="text-sm font-semibold text-emerald-600 hover:underline dark:text-emerald-400">View Details</button></div><div className="mt-4 grid grid-cols-2 gap-2"><button disabled={product.availability === "Out of Stock"} onClick={() => { addToCart(product.id); openModal("product-order"); }} className="inline-flex items-center justify-center gap-1 rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><ShoppingCart size={14} /> Order Now</button><a href={productWhatsapp(product, contact.whatsapp)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-1 rounded-xl bg-emerald-500/10 px-3 py-2 text-xs font-bold text-emerald-700 dark:text-emerald-400"><WhatsappLogo size={14} weight="fill" /> Ask on WhatsApp</a></div></div></article>;
}

export function StoreSection() {
  const { products, cart, openModal } = usePortfolio();
  const [active, setActive] = useState<(typeof categories)[number]>("All");
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState("newest");
  const filtered = products.filter((product) => (active === "All" || product.category === active) && `${product.name} ${product.brand} ${product.category}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "availability" ? Number(b.availability !== "Out of Stock") - Number(a.availability !== "Out of Stock") : sort === "price-low" ? Number(a.price.replace(/[^0-9.]/g, "")) - Number(b.price.replace(/[^0-9.]/g, "")) : sort === "price-high" ? Number(b.price.replace(/[^0-9.]/g, "")) - Number(a.price.replace(/[^0-9.]/g, "")) : b.createdAt.localeCompare(a.createdAt));
  const cartTotal = cart.reduce((sum, item) => sum + (numericPrice(products.find((product) => product.id === item.productId)?.price ?? "") * item.quantity), 0);
  return <section id="mifi-routers" className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading title="MIFI & ROUTERS" subtitle="Stay Connected With Reliable Internet Devices." /><div className="mb-8 flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><MagnifyingGlass size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search MiFi, routers and gadgets..." className={`${inputCls} pl-10`} /></label><select value={sort} onChange={(event) => setSort(event.target.value)} className={`${inputCls} lg:max-w-52`}><option value="newest">Newest</option><option value="availability">Availability</option><option value="price-low">Price: Low to High</option><option value="price-high">Price: High to Low</option></select><button onClick={() => openModal("product-order")} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white"><ShoppingCart size={18} /> Cart ({cart.reduce((sum, item) => sum + item.quantity, 0)})</button></div><div className="mb-8 flex gap-2 overflow-x-auto pb-1">{categories.map((category) => <button key={category} onClick={() => setActive(category)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${active === category ? "bg-emerald-500 text-white" : "border border-border bg-card text-muted-foreground"}`}>{category}</button>)}</div>{filtered.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((product) => <ProductCard key={product.id} product={product} onDetails={() => openModal("product-detail", product.id)} />)}</div> : <div className="rounded-2xl border border-dashed border-border bg-muted/20 p-12 text-center"><Package size={42} className="mx-auto mb-3 text-muted-foreground" /><h3 className="font-bold">No products available yet</h3><p className="mt-2 text-sm text-muted-foreground">Products will appear here after they are added and published by the administrator.</p></div>}<div className="mt-8 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border bg-card p-5"><div><div className="text-sm font-semibold">Cart total</div><div className="text-xs text-muted-foreground">{cartTotal ? `₦${cartTotal.toLocaleString()}` : "Confirmed after product availability review"}</div></div><a href="/products" className="rounded-xl border border-border px-4 py-2.5 text-sm font-bold hover:bg-accent">View All Products</a></div></div></section>;
}

function NinRequestForm() {
  const { modal, closeModal, ninServices, addNinRequest, contact } = usePortfolio();
  const service = ninServices.find((item) => item.id === modal.data);
  const [done, setDone] = useState(false);
  const [form, setForm] = useState({ name: "", phone: "", whatsapp: contact.whatsapp, email: "", service: service?.title ?? "", preferredDate: "", method: "Virtual" as "Virtual" | "Physical", notes: "" });
  const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.name.trim() || !form.phone.trim() || !form.email.trim() || !form.service) return; addNinRequest(form); setDone(true); };
  if (done) return <div className="py-6 text-center"><Check size={42} className="mx-auto mb-4 text-emerald-500" /><h4 className="text-xl font-bold">Request Received</h4><p className="mt-2 text-sm text-muted-foreground">Your NIN service request has been received. We will contact you shortly with the next steps.</p><button onClick={closeModal} className="mt-6 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white">Close</button></div>;
  return <form onSubmit={submit} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><input required className={inputCls} placeholder="Full Name" value={form.name} onChange={update("name")} /><input required className={inputCls} placeholder="Phone Number" value={form.phone} onChange={update("phone")} /><input className={inputCls} placeholder="WhatsApp Number" value={form.whatsapp} onChange={update("whatsapp")} /><input required type="email" className={inputCls} placeholder="Email" value={form.email} onChange={update("email")} /></div><select required className={inputCls} value={form.service} onChange={update("service")}><option value="">Select NIN service</option>{ninServices.filter((item) => item.enabled).map((item) => <option key={item.id} value={item.title}>{item.title}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Preferred Date<input type="date" className={`${inputCls} mt-1.5`} value={form.preferredDate} onChange={update("preferredDate")} /></label><label className="text-sm font-medium">Preferred Service Method<select className={`${inputCls} mt-1.5`} value={form.method} onChange={update("method")}><option>Virtual</option><option>Physical</option></select></label></div><textarea className={`${inputCls} min-h-24`} placeholder="Additional Information. Do not include your NIN, OTP, PIN or password." value={form.notes} onChange={update("notes")} /><div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-700 dark:text-amber-300"><ShieldCheck size={16} className="mb-1" />{NIN_SECURITY_NOTICE}</div><button className="w-full rounded-xl bg-emerald-500 py-3 font-bold text-white">Submit NIN Request</button></form>;
}

function CartOrderForm() {
  const { products, cart, updateCartQuantity, removeFromCart, clearCart, addProductOrder, closeModal, contact } = usePortfolio();
  const [done, setDone] = useState(false);
  const [form, setForm] = useState({ name: "", phone: "", whatsapp: contact.whatsapp, email: "", deliveryMethod: "Pickup" as "Pickup" | "Delivery", deliveryAddress: "", instructions: "" });
  const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const lines = cart.map((item) => ({ ...item, product: products.find((product) => product.id === item.productId) })).filter((item): item is typeof item & { product: Product } => Boolean(item.product));
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!lines.length || !form.name.trim() || !form.phone.trim() || !form.email.trim() || (form.deliveryMethod === "Delivery" && !form.deliveryAddress.trim())) return; lines.forEach((line) => addProductOrder({ ...form, productId: line.product.id, productName: line.product.name, quantity: line.quantity })); clearCart(); setDone(true); };
  if (done) return <div className="py-6 text-center"><Check size={42} className="mx-auto mb-4 text-emerald-500" /><h4 className="text-xl font-bold">ORDER REQUEST RECEIVED</h4><p className="mt-2 text-sm text-muted-foreground">Thank you for your order request. We have received your request and will contact you shortly to confirm product availability, pricing, delivery details and payment.</p><button onClick={closeModal} className="mt-6 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white">Continue Shopping</button></div>;
  return <form onSubmit={submit} className="space-y-4"><div className="space-y-2">{lines.length ? lines.map((line) => <div key={line.product.id} className="flex items-center gap-3 rounded-xl border border-border bg-card p-3"><div className="flex-1 text-sm font-semibold">{line.product.name}<div className="text-xs text-muted-foreground">{formatPrice(line.product.price)}</div></div><button type="button" onClick={() => updateCartQuantity(line.product.id, line.quantity - 1)}><Minus size={15} /></button><span className="text-sm">{line.quantity}</span><button type="button" onClick={() => updateCartQuantity(line.product.id, line.quantity + 1)}><Plus size={15} /></button><button type="button" onClick={() => removeFromCart(line.product.id)} className="text-red-500"><Trash size={15} /></button></div>) : <p className="rounded-xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">Your cart is empty.</p>}</div><div className="grid gap-3 sm:grid-cols-2"><input required className={inputCls} placeholder="Full Name" value={form.name} onChange={update("name")} /><input required className={inputCls} placeholder="Phone Number" value={form.phone} onChange={update("phone")} /><input className={inputCls} placeholder="WhatsApp Number" value={form.whatsapp} onChange={update("whatsapp")} /><input required type="email" className={inputCls} placeholder="Email" value={form.email} onChange={update("email")} /></div><select className={inputCls} value={form.deliveryMethod} onChange={update("deliveryMethod")}><option>Pickup</option><option>Delivery</option></select>{form.deliveryMethod === "Delivery" && <input required className={inputCls} placeholder="Delivery Address" value={form.deliveryAddress} onChange={update("deliveryAddress")} />}<textarea className={`${inputCls} min-h-20`} placeholder="Additional Instructions" value={form.instructions} onChange={update("instructions")} /><p className="text-xs text-muted-foreground">Delivery charges may apply depending on location.</p><button disabled={!lines.length} className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:opacity-40">Proceed to Order</button></form>;
}

function ProductDetail() {
  const { modal, products, addToCart, contact } = usePortfolio();
  const product = products.find((item) => item.id === modal.data);
  if (!product) return null;
  return <div className="space-y-5"><div className="aspect-video overflow-hidden rounded-2xl bg-muted">{product.imageUrl ? <img src={product.imageUrl} alt={product.name} className="size-full object-cover" /> : <div className="grid size-full place-items-center text-muted-foreground"><Package size={52} /></div>}</div><div><div className="text-sm text-muted-foreground">{product.brand} · {product.category}</div><h4 className="mt-1 text-2xl font-bold">{product.name}</h4><div className="mt-2 text-xl font-bold text-blue-600 dark:text-blue-400">{formatPrice(product.price)}</div></div><div className="rounded-xl border border-border bg-card p-4 text-sm"><div className="mb-2 font-semibold">Specifications</div>{product.specifications.length ? product.specifications.map((specification) => <div key={specification.label} className="flex justify-between gap-4 border-b border-border py-2 last:border-0"><span className="text-muted-foreground">{specification.label}</span><span className="text-right font-medium">{specification.value}</span></div>) : <p className="text-muted-foreground">Specifications will be provided by the administrator.</p>}</div><p className="text-sm leading-relaxed text-muted-foreground">{product.description || "Product details are available from the seller."}</p><div className="flex flex-wrap gap-2"><button disabled={product.availability === "Out of Stock"} onClick={() => addToCart(product.id)} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">Add to Cart</button><a href={productWhatsapp(product, contact.whatsapp)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-emerald-500/10 px-4 py-2.5 text-sm font-bold text-emerald-700 dark:text-emerald-400"><WhatsappLogo size={17} weight="fill" /> Chat on WhatsApp</a></div></div>;
}

export function NinAndStoreModals() {
  const { modal, closeModal } = usePortfolio();
  const title = modal.type === "nin-request" ? "Request NIN Service" : modal.type === "product-order" ? "Product Order" : "Product Details";
  if (!["nin-request", "product-order", "product-detail"].includes(modal.type ?? "")) return null;
  return <AnimatePresence><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[105] flex items-end justify-center bg-black/60 p-0 backdrop-blur-sm sm:items-center sm:p-4"><motion.div initial={{ y: 30, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl border border-border bg-background shadow-2xl sm:max-w-2xl sm:rounded-3xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-background/95 px-6 py-4 backdrop-blur"><div><h3 className="font-bold">{title}</h3><p className="text-xs text-muted-foreground">{modal.type === "nin-request" ? "We will contact you with the next steps." : "Availability and final pricing are confirmed before payment."}</p></div><button onClick={closeModal} className="grid size-9 place-items-center rounded-full bg-muted"><X size={18} /></button></div><div className="p-6">{modal.type === "nin-request" && <NinRequestForm />}{modal.type === "product-order" && <CartOrderForm />}{modal.type === "product-detail" && <ProductDetail />}</div></motion.div></motion.div></AnimatePresence>;
}

export function NinServicesPage() { return <main><NinServicesSection /></main>; }
export function ProductsPage() { return <main><StoreSection /></main>; }
